version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: crm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    build:
      context: ./app-backend
      dockerfile: Dockerfile
    container_name: backend
    depends_on:
      - postgres
    ports:
      - "8085:8080"  # Map host port 8085 to container port 8080 (as per Dockerfile)
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/crm
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root123
    restart: always

  frontend:
    build:
      context: ./app-frontend
      dockerfile: Dockerfile
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "3000:80"  # Map host port 3000 to container port 80 (Nginx default in Dockerfile)
    restart: always

volumes:
  postgres_data: