version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: crm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    image: backendjava  # <-- replace with your actual backend image name
    container_name: backend
    depends_on:
      - postgres
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/crm
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root123
    restart: always

  frontend:
    image: registry.gitlab.com/cyberstalk0210/forserver/frontend:latest
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    restart: always

volumes:
  postgres_data:
